[general]
import = ["~/.config/alacritty/themes/afterglow.toml"]

[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 25, y = 25 }
decorations = "Full"
opacity = 1.0
blur = true

[font]
normal = { family="ZedMono Nerd Font", style="Regular"}
size = 26.0


[bell]
animation = "Linear"
duration = 100


[cursor]
style = {shape="Block", blinking="Always"}
blink_interval = 1000000000 
