[general]
import = ["~/.config/alacritty/themes/dracula.toml"]

[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 30, y = 30 }
decorations = "Full"
opacity = 1 
blur = true


[font]
normal = { family="ZedMono Nerd Font", style="Bold"}
size = 28.5


[bell]
animation = "Linear"
duration = 10 


[cursor]
style = {shape="Block", blinking="Always"}
blink_interval = 1000000000 
